parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: workincloser
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 430e25539bb68d8ceb550f44758ad8d6d50ae66e
    database_path: null