ulipse_message:
    resource: "@UlipseMessageBundle/Controller/"
    type:     annotation
    prefix:   /

ulipse_workincloser:
    resource: "@UlipseWorkincloserBundle/Controller/"
    type:     annotation
    prefix:   /

ulipse_user:
    resource: "@UlipseUserBundle/Controller/"
    type:     annotation
    prefix:   /
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
